### ISSUE TITLE
null | undefined в параметрах

### ISSUE THREAD

**Issue by dmitriybo** [Ayub-Begimkulov/i18n#3]
Было бы здорово, если бы было можно передавать null | undefined в качестве параметра, и они бы выводились как пустая строка:

![image](https://user-images.githubusercontent.com/69904042/229592339-adab6224-fc2a-4906-af69-ffddff4a769a.png)

**Comment by Ayub-Begimkulov** [comment]
Привет. А можешь рассказать, чем тебе не нравится текущее API?

Если ты хочешь, чтобы у тебя показывалась пустая строка, вместо null/undefined - ты можешь сделать вот так:

```ts
translate('some_key', {
  param: getParam() || ''
});
```

Проблема того, что если в типизации будет undefined/null - то человек может не заметить ошибку.

И по возможности можешь писать на английском. Можно даже полностью через google translate.

**Comment by dmitriybo** [comment]
Ладно, если это создаст проблемы, то не надо
